/// English-only labels and helpers for PDF report generation.
///
/// These are intentionally NOT connected to AppStrings or any app i18n system.
/// Reports must always be generated in English regardless of the app's UI locale.
class PdfReportLabels {
  PdfReportLabels._();

  // ─── Branding ─────────────────────────────────────────────────────────────
  static const appName = 'Route Mint';
  static const simpleReportTitle = 'Route Mint Report';
  static const detailedReportTitle = 'Route Mint Mileage & Expense Report';
  static const reportTypeSimple = 'Simple';
  static const reportTypeDetailed = 'Detailed';
  static const reportDisclaimer =
      'Accountant-friendly mileage and expense report. '
      'Not certified for tax filing. Verify with a qualified tax professional.';
  static const generatedBy = 'Generated by Route Mint';
  static const monthlySummary = 'Monthly Summary';

  // ─── Meta fields ──────────────────────────────────────────────────────────
  static const period = 'Period';
  static const currency = 'Currency';
  static const distanceUnit = 'Distance Unit';
  static const reportType = 'Report Type';
  static const generatedOn = 'Generated';

  // ─── Summary section ──────────────────────────────────────────────────────
  static const summary = 'Summary';
  static const mileageGroup = 'Mileage';
  static const expensesGroup = 'Expenses';
  static const totalDistance = 'Total Distance';
  static const businessDistance = 'Business Distance';
  static const personalDistance = 'Personal Distance';
  static const totalShifts = 'Total Shifts';
  static const totalTrips = 'Total Trips';
  static const taxDeduction = 'Tax Deduction';

  // ─── Report identity ──────────────────────────────────────────────────────
  static const driver = 'Driver';
  static const business = 'Business';
  static const vehicle = 'Vehicle';

  // ─── Expenses ─────────────────────────────────────────────────────────────
  static const fuel = 'Fuel';
  static const parking = 'Parking';
  static const tolls = 'Tolls';
  static const totalExpenses = 'Total Expenses';

  // ─── Platform breakdown ───────────────────────────────────────────────────
  static const platformBreakdown = 'Platform Breakdown';
  static const platform = 'Platform';
  static const distance = 'Distance';

  // ─── Work shift expenses table ────────────────────────────────────────────
  /// Renamed from "Shift Details" because WorkShift does not yet store
  /// date, odometer, or driven distance. This will be updated when a
  /// real shift-log model is introduced.
  static const workShiftExpenses = 'Work Shift Expenses';
  static const start = 'Start';
  static const end = 'End';
  static const startTime = 'Start Time';
  static const endTime = 'End Time';
  static const total = 'Total';

  // ─── Trip details table ───────────────────────────────────────────────────
  static const tripDetails = 'Trip Details';
  static const date = 'Date';
  static const from = 'From';
  static const to = 'To';
  static const purpose = 'Purpose';
  static const startLocation = 'Start Location';
  static const endLocation = 'End Location';
  static const businessPurpose = 'Business Purpose';
  static const category = 'Category';
  static const notes = 'Notes';
  static const tripParkingTollsNote =
      'Trip-level parking and tolls will appear here when added to trip records.';

  // ─── Misc ─────────────────────────────────────────────────────────────────
  static const na = 'N/A';
  static const usd = 'USD';
  static const cad = 'CAD';
  static const pageOf = 'of';
  static const dash = '-';

  static const _months = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ];

  // ─── Currency helper ──────────────────────────────────────────────────────

  /// Formats a monetary amount with its ISO currency code prefix.
  /// Example: formatReportCurrency(123.45, 'USD') → "USD 123.45"
  static String formatReportCurrency(double amount, String currencyCode) {
    return '$currencyCode ${amount.toStringAsFixed(2)}';
  }

  // ─── Date helpers ─────────────────────────────────────────────────────────

  /// Formats a date in English accountant-friendly style.
  /// Example: March 1, 2026
  static String formatLongDate(DateTime date) {
    return '${_months[date.month - 1]} ${date.day}, ${date.year}';
  }

  /// Formats a report period range.
  /// Example: March 1, 2026 – March 31, 2026
  static String formatPeriod(DateTime start, DateTime end) {
    return '${formatLongDate(start)} $dash ${formatLongDate(end)}';
  }

  /// Returns a short month+year label used in file names and badge text.
  /// Example: March 2026
  static String formatMonthYear(DateTime date) {
    return '${_months[date.month - 1]} ${date.year}';
  }

  // ─── Business purpose helper ──────────────────────────────────────────────

  /// Derives a human-readable business purpose string from trip data.
  ///
  /// Rules:
  /// - business + platformName → "{platformName} business trip"
  /// - business, no platformName → "Business trip"
  /// - personal or other → "N/A"
  static String businessPurposeFor({
    required String category,
    String? platformName,
  }) {
    if (category != 'business') return na;
    if (platformName != null && platformName.isNotEmpty) {
      return '$platformName business trip';
    }
    return 'Business trip';
  }
}
