// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTEkO_fcrP1ovbQr1U7tu5lMeDYOV80Jw',
    appId: '1:1026475770254:web:bb53aafd01a45d7678e4df',
    messagingSenderId: '1026475770254',
    projectId: 'route-mint-app-2026',
    authDomain: 'route-mint-app-2026.firebaseapp.com',
    storageBucket: 'route-mint-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXLRVyEV5XzhYr6GT_N0uefCanuug-vkc',
    appId: '1:1026475770254:android:aefb47680c3f06d178e4df',
    messagingSenderId: '1026475770254',
    projectId: 'route-mint-app-2026',
    storageBucket: 'route-mint-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2jTTS9scZPenpuHu-Z5Vz90hix9-SNks',
    appId: '1:1026475770254:ios:5f39a17acf6528d678e4df',
    messagingSenderId: '1026475770254',
    projectId: 'route-mint-app-2026',
    storageBucket: 'route-mint-app-2026.firebasestorage.app',
    iosBundleId: 'com.marvroute.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2jTTS9scZPenpuHu-Z5Vz90hix9-SNks',
    appId: '1:1026475770254:ios:5f39a17acf6528d678e4df',
    messagingSenderId: '1026475770254',
    projectId: 'route-mint-app-2026',
    storageBucket: 'route-mint-app-2026.firebasestorage.app',
    iosBundleId: 'com.marvroute.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTEkO_fcrP1ovbQr1U7tu5lMeDYOV80Jw',
    appId: '1:1026475770254:web:06a57b1295b950b078e4df',
    messagingSenderId: '1026475770254',
    projectId: 'route-mint-app-2026',
    authDomain: 'route-mint-app-2026.firebaseapp.com',
    storageBucket: 'route-mint-app-2026.firebasestorage.app',
  );
}
